### ISSUE TITLE
Cache fails with files with spaces?

### ISSUE THREAD

**Issue by shish** [awalsh128/cache-apt-pkgs-action#85] opened 2023-01-05 19:06 UTC
Looks like `tar` is being passed a list of filenames un-quoted, so files with spaces in the filenames break it?

eg https://github.com/shish/rosettaboy/actions/runs/3849566460/jobs/6558711183

```
19:00:40 Caching 57 installed packages...
19:00:40   * Caching libjsoncpp25 to /home/runner/cache-apt-pkgs/libjsoncpp25:1.9.5-3.tar...
19:00:40     done (compressed size 232K).
19:00:40   * Caching librhash0 to /home/runner/cache-apt-pkgs/librhash0:1.4.2-1ubuntu1.tar...
19:00:40     done (compressed size 212K).
19:00:40   * Caching dh-elpa-helper to /home/runner/cache-apt-pkgs/dh-elpa-helper:2.0.9ubuntu1.tar...
19:00:40     done (compressed size 20K).
19:00:40   * Caching cmake-data to /home/runner/cache-apt-pkgs/cmake-data:3.22.1-1ubuntu1.22.04.1.tar...
tar: usr/share/cmake-3.22/Help/generator/Borland: Cannot stat: No such file or directory
tar: Makefiles.rst: Cannot stat: No such file or directory
tar: usr/share/cmake-3.22/Help/generator/Eclipse: Cannot stat: No such file or directory
tar: CDT4.rst: Cannot stat: No such file or directory
[...]
```

**Comment by awalsh128** [comment] 2023-01-05 19:50
This was addressed in #81 but `v1.2.2` is not marked latest due to some cache issues found that are still pending. It may be related to that release but nothing has been confirmed. Worst case is that you can bump the `version` on `v1.2.2`.

**Closed** 2023-01-06 17:44 UTC
