### ISSUE TITLE
ls: cannot access '/home/runner/cache-apt-pkgs/*.tar': No such file or directory

### ISSUE THREAD

**Issue by Marwennnne** [awalsh128/cache-apt-pkgs-action#82] opened 2023-01-03 12:36 UTC
My problem is quite simple actually when I used this method to cache the package `vault`. it was compressed into this file `vault:1.12.2-1.tar.gz` so when this method tries to fetch all the compressed packages it won't find it since the search command is `cached_pkg_filepaths=$(ls -1 "${cache_dir}"/*.tar | sort)`

**Comment by 0ssigeno** [comment] 2023-01-03 14:00
Adding that this error was not present prior version 1.2.2.

**Comment by schlomo** [comment] 2023-01-03 15:37
I have the same problem, any ideas?

**Comment by awalsh128** [comment] 2023-01-03 23:33
Sorry to hear this. Go back to v1.2.1 and confirm if this fixes it. I may revert the `latest` and `v1` tags if this is a new bug introduced in the release.

**Comment by awalsh128** [comment] 2023-01-04 06:41
FYI, I reverted the tags. This looks like a dupe of #83 but I am going to leave open until I can confirm.

**Comment by awalsh128** [comment] 2023-01-09 04:46
@schlomo and @Marwennnne I believe this was from an older release awhile ago where compression was pulled since the cache actions already compresses and removing would speed it up. Bumping the input version fixes the issue. Did either of you upgrade recently?

**Comment by schlomo** [comment] 2023-01-09 09:14
I tried using `latest` and then did a "regular" `apt-get install` step as I didn't have time to debug this and was trying it out to get a one-liner for installing dependencies.

**Comment by martinling** [comment] 2023-01-09 18:44
I am using `latest` and still seeing this issue, despite bumping the cache version after @awalsh128's comment saying the tags had now been reverted.

The failure can be seen in the CI run for my commit bumping the cache version, which is here: https://github.com/greatscottgadgets/packetry/pull/54/commits/238efab32a884048b93a8624494e0a63a32dbcd5

**Comment by martinling** [comment] 2023-01-17 16:29
It seems that reverting the `latest` tag did not cause GitHub Actions to revert workflows using that tag to the older version. I had to explicitly target `v1.2.1` and bump the cache version to avoid this bug, as in the PR linked above.

Note that the `v1` tag is [currently](https://github.com/awalsh128/cache-apt-pkgs-action/tags) still pointing to the broken `v1.2.2` release. Only the `latest` tag was reverted.

**Comment by martinling** [comment] 2023-01-17 16:40
Sorry, my mistake - it's fine to use `latest` with a cache version bump, I'd just forgotten to bump the version on a second use of the action.

However, the other info in my previous comment is correct - `v1` still points to the broken release.

**Comment by awalsh128** [comment] 2023-02-03 20:20
Sorry for the long lag here. To avoid other people encountering this and having to manually fix, I am going to add a feature to automatically refresh the catch when breaking changes are encountered. I'll update this issue once I have something ready.

**Comment by awalsh128** [comment] 2023-02-03 21:06
Okay issued a patch so this doesn't happen again. All tags are rev'd at current release.

**Closed by awalsh128** 2023-02-03 21:06 UTC

**Comment by nwalters512** [comment] 2025-05-20 00:52
I hate to revive such an old issue, but I just saw two CI failures caused by exactly this. We're using 1.5.0 of this action.

Here are the relevant jobs and bits of their output:

https://github.com/PrairieLearn/PrairieLearn/actions/runs/15126128873/job/42518423527

```
Cache hit for: cache-apt-pkgs_cf256ed21c9e16f5880106e6d7272ff9
Received 449 of 449 (100.0%), 0.0 MBs/sec
Cache Size: ~0 MB (449 B)
/usr/bin/tar -xf /home/runner/work/_temp/360a6541-[45](https://github.com/PrairieLearn/PrairieLearn/actions/runs/15126128873/job/42518423527?pr=11989#step:3:48)47-43f0-a906-c366aca1330b/cache.tzst -P -C /home/runner/work/PrairieLearn/PrairieLearn --use-compress-program unzstd
Cache restored successfully
Cache restored from key: cache-apt-pkgs_cf256ed21c9e16f5880106e6d7272ff9
Run ${GITHUB_ACTION_PATH}/post_cache_action.sh \
Found 3 files in the cache.
- cache_key.md5
- install.log
- manifest_main.log

Reading from main requested packages manifest...
- graphviz=2.42.2-9ubuntu0.1
- libgraphviz-dev=2.42.2-9ubuntu0.1
done

ls: cannot access '/home/runner/cache-apt-pkgs/*.tar': No such file or directory
Restoring 0 packages from cache...
done

cat: /home/runner/cache-apt-pkgs/manifest_all.log: No such file or directory
/home/runner/work/_temp/c8051235-a804-4386-9[46](https://github.com/PrairieLearn/PrairieLearn/actions/runs/15126128873/job/42518423527?pr=11989#step:3:49)c-5c7e3f79418b.sh: line 8: -1: substring expression < 0
```

https://github.com/PrairieLearn/PrairieLearn/actions/runs/15126128873/job/42518423520

```
Cache hit for: cache-apt-pkgs_e7468feb68a7c6883be7ea0056333d73
Received [45](https://github.com/PrairieLearn/PrairieLearn/actions/runs/15126128873/job/42518423520?pr=11989#step:3:48)1 of 451 (100.0%), 0.0 MBs/sec
Cache Size: ~0 MB (451 B)
/usr/bin/tar -xf /home/runner/work/_temp/1aa5afdc-2495-4795-b8ac-88dbae7cce18/cache.tzst -P -C /home/runner/work/PrairieLearn/PrairieLearn --use-compress-program unzstd
Cache restored successfully
Cache restored from key: cache-apt-pkgs_e7[46](https://github.com/PrairieLearn/PrairieLearn/actions/runs/15126128873/job/42518423520?pr=11989#step:3:49)8feb68a7c6883be7ea0056333d73
Run ${GITHUB_ACTION_PATH}/post_cache_action.sh \
Found 3 files in the cache.
- cache_key.md5
- install.log
- manifest_main.log

Reading from main requested packages manifest...
- git-restore-mtime=2022.12-1
done

ls: cannot access '/home/runner/cache-apt-pkgs/*.tar': No such file or directory
Restoring 0 packages from cache...
done

cat: /home/runner/cache-apt-pkgs/manifest_all.log: No such file or directory
/home/runner/work/_temp/d9d0d189-9513-43fa-b3f5-04d0ea92[71](https://github.com/PrairieLearn/PrairieLearn/actions/runs/15126128873/job/42518423520?pr=11989#step:3:75)46.sh: line 8: -1: substring expression < 0
```
